FROM python:3.12-slim

WORKDIR /workspace

COPY pyproject.toml README.md ./
COPY app ./app
COPY config ./config
COPY data ./data

RUN python -m pip install --upgrade pip && \
    python -m pip install -e .

EXPOSE 8501
