FROM python:3.12-slim

WORKDIR /workspace

COPY pyproject.toml README.md ./
COPY app ./app
COPY alembic ./alembic
COPY alembic.ini ./
COPY scripts ./scripts
COPY config ./config
COPY data ./data
COPY docs ./docs

RUN python -m pip install --upgrade pip && \
    python -m pip install -e .

EXPOSE 8000
